services:

    db_prod:
        image:
            postgres:18
        ports:
            - "5432:5432"
        env_file:
            - ".env.prod"
        networks:
            - my_network
        volumes:
            - db_pro_data:/var/lib/postgrsql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            .
        ports:
            - "8000:8000"
        env_file:
            - ".env.prod"
        networks:
            - my_network
        depends_on:
            db_prod:
                condition: service_healthy
        command:
            ["sh", "-c", "python3 -m alembic upgrade head && python3 -m src.main "]




networks:
    my_network:

volumes:
    db_pro_data:
