services:

    db_prod:
        image:
            postgres:18
        ports:
            - "5432:5432"
        env_file:
            - ".env.prod"
        networks:
            - my_network
        volumes:
            - db_prod_data:/var/lib/postgrsql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            .
        ports:
            - "8000:8000"
        env_file:
            - ".env.prod"
        networks:
            - my_network
        depends_on:
            db_prod:
                condition: service_healthy
            redis:
                condition: service_started
        command:
            ["sh", "-c", "python3 -m alembic upgrade head && python3 -m src.main "]

    redis:
        image:
            redis:latest
        ports:
            - "6379:6379"
        env_file:
            - ".env.prod"
        networks:
            - my_network
        volumes:
            - redis_data:/data

    celery_worker:
        build:
            .
        env_file:
            - ".env.prod"
        networks:
            - my_network
        command: ["sh", "-c", "celery --app=src.tasks.celery_app:celery_instance worker -l info"]

    celery_beat:
        build:
            .
        env_file:
            - ".env.prod"
        networks:
            - my_network
        command: ["sh", "-c", "celery --app=src.tasks.celery_app:celery_instance beat -l info"]


networks:
    my_network:

volumes:
    db_prod_data:
    redis_data:
